# Generated by Django 5.0.2 on 2024-05-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_company_website_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_website_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ticket_manager_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_homepage_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='tickets_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_management_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
